package com.simplilearn.jdbc;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Scanner;

import com.simplilearn.jdbc.bean.User;

public class _05_PrStInsert {

    public static void main(String[] args) {

        String dbUrl = "jdbc:mysql://localhost:3306/mydb";
        String dbUsername = "root";
        String dbPassword = "rootroot";

        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        User user = new User();

        /*
         * Read the data from the User.
         */
        try(Scanner scan= new Scanner(System.in)){

            System.out.println("Enter the username: ");
            user.setUsername(scan.nextLine());

            System.out.println("Enter the password: ");
            user.setPassword(scan.nextLine());

            System.out.println("Enter the first name: ");
            user.setFirstName(scan.nextLine());

            System.out.println("Enter the last name: ");
            user.setLastName(scan.nextLine());

            System.out.println("Enter the date of birth (yyyy-MM-dd): ");
            user.setBirth(formatter.parse(scan.nextLine()));

            System.out.println("Enter the status: ");
            user.setStatus(scan.nextLine());

        } catch (ParseException ex) {
            System.err.println("Error while reading input: " + ex.getMessage());
            System.exit(-1);
        }

        System.out.println(user);

        /*
         * Create the Insert SQL Statement
         */
        String sql = "INSERT INTO USER (USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, BIRTH, STATUS) "
                   + "VALUES(?,?,?,?,?,?)";

        System.out.println("Query: " + sql);

        /*
         * Insert the data into the DB table;
         */
        try(Connection con = DriverManager.getConnection(dbUrl, dbUsername, dbPassword);
            PreparedStatement prSt = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            prSt.setString(1, user.getUsername());
            prSt.setString(2, user.getPassword());
            prSt.setString(3, user.getFirstName());
            prSt.setString(4, user.getLastName());
            /*
             * We need to convert from java.util.Date into java.sql.Date.
             *  - user.getBirth() returns a java.util.Date
             */
            prSt.setDate(5, new Date(user.getBirth().getTime()));
            prSt.setString(6, user.getStatus());

            int rows = prSt.executeUpdate();

            System.out.println("Number of rows affected: " + rows);

            /*
             * Get the primary key generated by the DB for the new inserted row.
             */
            try(ResultSet resultSet = prSt.getGeneratedKeys()){

                if (resultSet.first()) {
                	
                    user.setIdUser(resultSet.getInt(1)); // Get the primary key from the ResultSet.
                    System.out.println(user); // Print out the user with userId
                }
            }

        } catch (SQLException ex) {

            System.err.println("Error while connecting! , " + ex.getSQLState() + ", " + ex.getMessage());
        }
    }

}
